@LuckySpin_HostAddress = http://localhost:5074


### In campaign
GET {{LuckySpin_HostAddress}}/api/campaigns/admin
Accept: application/json

### Campaign by id
GET {{LuckySpin_HostAddress}}/api/campaigns/admin/getcambyid/Cam002
Accept: application/json


### Add campaign --------------------------------CRUD
POST {{LuckySpin_HostAddress}}/api/campaigns/admin/addcampaign
Content-Type: application/json
{
  "Id": "Cam004",
  "CampaignName": "Hè 2028",
  "StartAt": "2026-01-01T00:00:00",
  "EndAt": "2026-12-01T00:00:00"
}

### Delete campaign
DELETE {{LuckySpin_HostAddress}}/api/campaigns/admin/deletecampaign/Cam001
Accept: application/json



### Change campaign info 
POST {{LuckySpin_HostAddress}}/api/campaigns/admin/changecampaigninfo/Cam001/2026-01-01T00:00:00/2026-12-01T00:00:00
Accept: application/json


### Add prize in Campaign
POST {{LuckySpin_HostAddress}}/api/campaigns/admin/addprize
Content-Type: application/json
{
  "Id": "Prize007",
  "Name": "Prize name 3",
  "CampaignId": "Cam001",      
  "PrizeType": "PHYSICAL",
  "ProbabilityWeight": 50,
  "Quantity": 1,
  "IsActive": true,             
  "CreatedAt": "2026-01-01T00:00:00",
  "SignatureKey": "PRIZENAME3"
}
###-----------------------------------------------CRUD


