@LuckySpin_HostAddress = http://localhost:5074


###
GET {{LuckySpin_HostAddress}}/api/prize/getprizes
Accept: application/json

### In store
GET {{LuckySpin_HostAddress}}/api/stores/admin
Accept: application/json

### Store by id
GET {{LuckySpin_HostAddress}}/api/stores/admin/getstorebyid/S001
Accept: application/json


### Add store --------------------------------CRUD
POST {{LuckySpin_HostAddress}}/api/stores/admin/addstore
Content-Type: application/json
{
  "Id": "S001",
  "StoreLocate": "123 Duong ABC, Quan 2"
}

### Delete store
DELETE {{LuckySpin_HostAddress}}/api/stores/admin/deletestore/S001
Accept: application/json

### Change store info
POST {{LuckySpin_HostAddress}}/api/stores/admin/changestoreinfo/S001/TPHCM
Accept: application/json
###--------------------------------------------CRUD


### Add prize in Campaign
POST {{LuckySpin_HostAddress}}/api/stores/admin/addprizetostore
Content-Type: application/json
{
  "Id": "Prize008",
  "Name": "Sandal Shoe Plus",
  "CampaignId": "Cam001",      
  "PrizeType": "PHYSICAL",
  "ProbabilityWeight": 0,
  "Quantity": 1,
  "IsActive": true,             
  "CreatedAt": "2026-01-01T00:00:00",
  "SignatureKey": "PRIZENAME2",
  "StoreId": "S001"
}

### Get Prize in Campaign store
GET {{LuckySpin_HostAddress}}/api/stores/admin/storecampaignprize/S001/Cam001
Accept: application/json

### Change probability in Campaign prize 
POST {{LuckySpin_HostAddress}}/api/stores/admin/changeprobability
Content-Type: application/json
{
    "StoreId": "S001",
    "CampaignId": "Cam001",
    "PrizeName": "SandalShoePremier",
    "NewProbabilityWeight": "20"
}

### New Campaign in store
POST {{LuckySpin_HostAddress}}/api/stores/admin/addcampaigntostore/S001/Cam001
Accept: application/json

### Remove Campaign in store
DELETE {{LuckySpin_HostAddress}}/api/stores/admin/removecampaignfromstore/S001/Cam002
Accept: application/json

### export
GET {{LuckySpin_HostAddress}}/api/stores/admin/export-excel
Accept: application/json




### import
POST {{LuckySpin_HostAddress}}/api/stores/admin/import-excel
Accept: application/json