@LuckySpin_HostAddress = http://localhost:5074


###
GET {{LuckySpin_HostAddress}}/api/prize/getprizes
Accept: application/json


###
POST {{LuckySpin_HostAddress}}/api/prize/resetprizes
Accept: application/json


########################    BILL    ###############################

### In bill
GET {{LuckySpin_HostAddress}}/api/bills
Accept: application/json

### Byid
GET {{LuckySpin_HostAddress}}/api/bills/Bill001
Accept: application/json

### Xóa bill
DELETE {{LuckySpin_HostAddress}}/api/bills/Bill001
Accept: application/json

### Test tạo bill mới
POST {{LuckySpin_HostAddress}}/api/bills/pos/newbill
Content-Type: application/json
{
  "id": "Bill007",
  "storeId": "S003",
  "storeLocate": "Store locate 003",
  "totalAmount": 300000.00,
  "paymentMethod": "online",
  "products": [
    { "id": "Product013", "name": "product13", "quantity": 1 },
    { "id": "Product014", "name": "product14", "quantity": 1 }
  ]
}




#######################    Product    ###################################

### In product
GET {{LuckySpin_HostAddress}}/api/products
Accept: application/json









#######################     Merchant   ####################################

### Store by id
GET {{LuckySpin_HostAddress}}/api/stores/getstorebyid/S001
Accept: application/json





#######################     Spin       ####################################

### Nhap ma quay thuong
POST {{LuckySpin_HostAddress}}/api/spin/spinaction
Content-Type: application/json
{
  "rewardCode": "LUCKY-784738D3",
  "campaignId": "Cam001"
}





#######################     Winner     ####################################

### Test tạo Winner Session mới
POST {{LuckySpin_HostAddress}}/api/WinnerSessions
Content-Type: application/json

{
  "fullName": "Nguyen Van C",
  "phone": "0901234456",
  "email": "nguyenvanc@gmail.com",
  "address": "Quan 2, TP.HCM"
}

### Nhan hang
POST {{LuckySpin_HostAddress}}/api/WinnerSessions/AssignWinnerToPrize
Content-Type: application/json

{
  "WinnerId": "CUSTOMER-0C105D8C",
  "PrizeId": "Prize001"
}

### In
GET {{LuckySpin_HostAddress}}/api/WinnerSessions/GetCustomerList
Accept: application/json

### Get customerinfo by phone
GET {{LuckySpin_HostAddress}}/api/WinnerSessions/GetByPhoneNumber/111111111
Accept: application/json

### Get prizes by customerid
GET {{LuckySpin_HostAddress}}/api/WinnerSessions/GetCustomerPrizeById/CUSTOMER-C8DDE2AF
Accept: application/json

###############################################################


